-- Insert all 26 award categories
-- Run this script in Supabase SQL Editor after creating tables and enabling RLS
-- Note: Category 25 is missing from the source data

INSERT INTO categories (id, title, nominees) VALUES
(1, 'FOODIE OF OIZOM', '{"A": "YASH CHAUHAN", "B": "AARSH PATEL", "C": "JAINAM MEHTA", "D": "PRIYANKA CHAKRAVORTY"}'),
(2, 'EVERYONE KNOWS THEM AWARD', '{"A": "SOHIL PATEL", "B": "JAINAM MEHTA", "C": "BHAVY SHAH", "D": "KAREENA SHARMA"}'),
(3, 'CAMERA READY ICON', '{"A": "HETANSHI GAJJAR", "B": "DRASHYA THAKKER", "C": "SHRUTI MATHUR", "D": "AJAY DUBEY"}'),
(4, 'MEME SUPPLIER', '{"A": "ARYA RAVAL", "B": "RASHIKA STIOKE", "C": "VARUN MEWADA", "D": "SHIVAM TRIPATHI"}'),
(5, 'SILENT BUT DEADLY', '{"A": "BHAGIRATH PATEL", "B": "KATHAN PANDYA", "C": "PRIYANKA LALWANI", "D": "JUHI SHETH"}'),
(6, 'PHONE NEVER SLEEPS AWARD', '{"A": "RUCHIK JANI", "B": "MEHUL PRAJAPATI", "C": "SOURISH BANERJEE", "D": "JAGRUTI PARMAR"}'),
(7, 'CTRL+ C CTRL+V CHAMP', '{"A": "DHEERAJ BUNKAR", "B": "SMIT PAREKH", "C": "HIRAL BASIYA", "D": "URVISHA GARNARA"}'),
(8, 'DANCE FLOOR DESTROYER', '{"A": "ISHITA OZA", "B": "PREKSHA SINGANE", "C": "RAHUL SAWANT", "D": "DRASHYA THAKKER"}'),
(9, 'GOSSIP BOY OF OIZOM', '{"A": "SAMARPIT GARG", "B": "JAINAM MEHTA", "C": "HARESH VAGHELA", "D": "DHARMENDRA PARMAR"}'),
(10, 'GOSSIP GIRL OF OIZOM', '{"A": "NISHI SHAH", "B": "SHIKSHA SLURIA", "C": "MANSI GOHIL", "D": "PAREESHA MODI"}'),
(11, 'ALWAYS GIVING GYAAN', '{"A": "MEHUL PRAJAPATI", "B": "VRUSHANK VYAS", "C": "SHRIDATT DUDHAT", "D": "SHEELESH PANDEY"}'),
(12, 'CONFUSION IS CONSTANT', '{"A": "KRISHNA ANOVADIYA", "B": "DHAVAL KALSARIYA", "C": "KAREENA SHARMA", "D": "KULDEEP ZALA"}'),
(13, 'HUMAN ALARM CLOCK', '{"A": "MANSI GOHIL", "B": "DIKSHIT THAKKAR", "C": "DEV PATEL", "D": "HEMDAS SOLANKI"}'),
(14, 'OVER PREPARED ONE', '{"A": "AARSH PATEL", "B": "KRUTI DAVDA", "C": "VISHAKHA MOTWANI", "D": "SHRUTI GUPTA"}'),
(15, 'ASTHETIC ACE', '{"A": "ARYA RAVAL", "B": "HETANSHI GAJJAR", "C": "DRASHYA THAKKER", "D": "RUTU BHANUSHALI"}'),
(16, 'LAST ONE AWAKE', '{"A": "JAINAM MEHTA", "B": "DIKSHIT THAKKAR", "C": "SHIVAM TRPATHI", "D": "YASH CHAUHAN"}'),
(17, 'MOST DRAMATIC REACTIONS', '{"A": "SHIKSHA SLURIA", "B": "SAMARPIT GARG", "C": "NISHI SHAH", "D": "SHRUTI MATHUR"}'),
(18, 'CEO OF LATE ENTRY', '{"A": "DHRUSHI PANSURIYA", "B": "PRIYANKA CHAKRAVORTY", "C": "BHUMIK NAYAK", "D": "RUCHIK JANI"}'),
(19, 'OFFICE THERAPIST', '{"A": "NISHI SHAH", "B": "KRUTI DAVDA", "C": "VRUSHANK VYAS", "D": "RANING LAKHNOTRA"}'),
(20, 'LAPTOP IN THE BAG AWARD', '{"A": "SOHIL PATEL", "B": "SHRIDATT DUDHAT", "C": "KRUTI DAVDA", "D": "BHUMIK NAYAK"}'),
(21, 'SLEEP ANYWHERE AWARD', '{"A": "SOHIL PATEL", "B": "PARTH GADARIA", "C": "RAHUL SAWANT", "D": "ISHIKA MULANI"}'),
(22, 'OVER EXPLAINER AWARD', '{"A": "MEHUL PRAJAPATI", "B": "JAGRUTI PARMAR", "C": "SOHIL PATEL", "D": "MAYUR VAGHELA"}'),
(23, 'MOOD SWING EXPRESS', '{"A": "KRISHNA ANOVADIYA", "B": "HIRAL BASIYA", "C": "HEMDAS SOLANKI", "D": "KAREENA SHARMA"}'),
(24, 'MULTITASKER OF OIZOM', '{"A": "BHAVY SHAH", "B": "DIKSHIT THAKKAR", "C": "KRUTI DAVDA", "D": "AARSH PATEL"}'),
(26, 'CHIEF COMPLAINT OFFICER (CCO)', '{"A": "MEHUL PRAJAPATI", "B": "PRIYANKA CHAKRAVORTY", "C": "KAREENA SHARMA", "D": "SAMARPIT GARG"}'),
(27, 'ANGRY BIRD', '{"A": "SAMARPIT GARG", "B": "RAHUL SAWANT", "C": "AJAY DUBEY", "D": "RUCHIK JANI"}');
